### ISSUE TITLE
ERROR in production

### ISSUE THREAD

**Issue by RobRuana** [rams/barcode#14]
```
   Traceback (most recent call last):
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 315, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 148, in csvout
        func(self, csv.writer(writer), session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/site_sections/summary.py", line 210, in printed_badges_staff
        generate_staff_badges(start_badge, end_badge, out, session)
      File "/usr/local/uber/plugins/uber/uber/site_sections/summary.py", line 14, in generate_staff_badges
        .run(out, session)
      File "/usr/local/uber/plugins/uber/uber/reports.py", line 65, in run
        self.write_row([badge_num, self._badge_type_name, empty_customized_name], out)
      File "/usr/local/uber/plugins/barcode/barcode/__init__.py", line 19, in write_row
        barcode = generate_barcode_from_badge_num(badge_num)
      File "/usr/local/uber/plugins/barcode/barcode/barcode_utils.py", line 62, in generate_barcode_from_badge_num
        raise ValueError('key length should be exactly 10 bytes, length={}'.format(len(key)))
    ValueError: key length should be exactly 10 bytes, length=0
```

**Comment by RobRuana** [comment]
BARCODE STRIKES AGAIN!

This issue was resolved by adding a `event-magstock.yaml` file on mcp with a new secret barcode key.
